name = "measure-text-worker"
main = "src/index.js"
compatibility_date = "2025-09-02"
compatibility_flags = ["nodejs_compat"]

# No longer need WASM rules

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[rules]]
type = "Data"
globs = ["assets/**/*.ttf"]
fallthrough = true

[env.production]
name = "measure-text-worker"